// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwxR7LHFuBnW2eES5vSm7bBdVlI_8w5Do',
    appId: '1:730401910892:web:80331cf1fb3c4a18e46849',
    messagingSenderId: '730401910892',
    projectId: 'book-shopping-app-ccbfc',
    authDomain: 'book-shopping-app-ccbfc.firebaseapp.com',
    storageBucket: 'book-shopping-app-ccbfc.firebasestorage.app',
    measurementId: 'G-QW654ME8K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeoHDATx2DvCHJfI75ep5MjPRz1PZpnTA',
    appId: '1:730401910892:android:357c2ae01eb785cee46849',
    messagingSenderId: '730401910892',
    projectId: 'book-shopping-app-ccbfc',
    storageBucket: 'book-shopping-app-ccbfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXoUbmq_RGHk1CDxeBbYrVX5o4h1MI4FE',
    appId: '1:730401910892:ios:0948b56ca46b134ee46849',
    messagingSenderId: '730401910892',
    projectId: 'book-shopping-app-ccbfc',
    storageBucket: 'book-shopping-app-ccbfc.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXoUbmq_RGHk1CDxeBbYrVX5o4h1MI4FE',
    appId: '1:730401910892:ios:0948b56ca46b134ee46849',
    messagingSenderId: '730401910892',
    projectId: 'book-shopping-app-ccbfc',
    storageBucket: 'book-shopping-app-ccbfc.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwxR7LHFuBnW2eES5vSm7bBdVlI_8w5Do',
    appId: '1:730401910892:web:16bff501acd1444de46849',
    messagingSenderId: '730401910892',
    projectId: 'book-shopping-app-ccbfc',
    authDomain: 'book-shopping-app-ccbfc.firebaseapp.com',
    storageBucket: 'book-shopping-app-ccbfc.firebasestorage.app',
    measurementId: 'G-V9QJZFTCLG',
  );
}
